version: '3'
services:
  fileutilsapp:
    container_name: fileutilsapp
    restart: always
    build: ../../../
    volumes:
      - ../../../data/fileutils/logs:/home/bot/app/logs
      - ../../../data/shr:/tmp/shr
      - ../../../data/botapi/workdir:/home/bot/app/botapi/workdir
    ports:
      - 5005:5005
    env_file:
      - .env

networks:
  default:
    external:
      name: fileutils
