version: '3'
services:
  renamerapp:
    container_name: renamerapp
    restart: always
    build: ../../../../renamer/
    volumes:
      - ../../../data/renamer/logs:/home/bot/app/logs
      - ../../../data/shr:/tmp/shr
    ports:
      - 5006:5005
    env_file:
      - .env.renamer
    depends_on:
      - renamerredis
      - renamermtproto
      - renamerbotapi
  renamerredis:
    container_name: renamerredis
    image: redis:alpine
    restart: always
    command:
      - 'redis-server'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
    volumes:
      - ../../../data/renamer/redis:/data
  renamermtproto:
    container_name: renamermtproto
    restart: always
    build: ../../../../fileutils-rest/
    env_file:
      - .env.renamer
    volumes:
      - ../../../data/renamer/gram:/home/bot/app/gram
      - ../../../data/shr:/tmp/shr
    depends_on:
      - renamerbotapi
  renamerbot:
    container_name: renamerbot
    restart: always
    build: ../../../../fileutils-bot/
    env_file:
      - .env.renamer
    volumes:
      - ../../../data/renamer/gram:/home/bot/app/gram
    depends_on:
      - renamerapp
  renamerbotapi:
    container_name: renamerbotapi
    restart: always
    build: ../../../../fileutils-bot-api/
    env_file:
      - .env.renamer
    volumes:
      - ../../../data/renamer/logs:/app/logs
      - ../../../data/shr:/tmp/shr
networks:
  default:
    external:
      name: fileutils