version: '3'
services:
  fapp:
    container_name: fapp
    restart: always
    build: ../../../
    volumes:
      - ${PWD}/data/logs:/app/logs
      - ${PWD}/data/license:/app/license
    env_file:
      - .env
  fdb:
    container_name: fdb
    image: postgres:alpine
    restart: always
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .db.env
  fredis:
    container_name: fredis
    image: redis:alpine
    restart: always
    command:
      - 'redis-server'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
    volumes:
      - ${PWD}/data/redis:/data